[2023-09-28T14:14:43.193+0700] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crawl_dag_v01.run_my_async_task scheduled__2023-09-22T00:40:00+00:00 [queued]>
[2023-09-28T14:14:43.237+0700] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crawl_dag_v01.run_my_async_task scheduled__2023-09-22T00:40:00+00:00 [queued]>
[2023-09-28T14:14:43.240+0700] {taskinstance.py:1359} INFO - Starting attempt 1 of 6
[2023-09-28T14:14:43.326+0700] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): run_my_async_task> on 2023-09-22 00:40:00+00:00
[2023-09-28T14:14:43.336+0700] {standard_task_runner.py:57} INFO - Started process 1007 to run task
[2023-09-28T14:14:43.440+0700] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'crawl_dag_v01', 'run_my_async_task', 'scheduled__2023-09-22T00:40:00+00:00', '--job-id', '110', '--raw', '--subdir', 'DAGS_FOLDER/crawlInvest.py', '--cfg-path', '/tmp/tmpmzkpac4q']
[2023-09-28T14:14:43.459+0700] {standard_task_runner.py:85} INFO - Job 110: Subtask run_my_async_task
[2023-09-28T14:14:43.781+0700] {task_command.py:415} INFO - Running <TaskInstance: crawl_dag_v01.run_my_async_task scheduled__2023-09-22T00:40:00+00:00 [running]> on host 052a1d3faae2
[2023-09-28T14:14:44.146+0700] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='linhhv' AIRFLOW_CTX_DAG_ID='crawl_dag_v01' AIRFLOW_CTX_TASK_ID='run_my_async_task' AIRFLOW_CTX_EXECUTION_DATE='2023-09-22T00:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-22T00:40:00+00:00'
[2023-09-28T14:14:44.182+0700] {logging_mixin.py:151} INFO - ['ASG', 'BAX', 'BCF', 'BSA', 'BSH', 'DHB', 'DP2', 'DSG', 'DTK', 'EIC']
[2023-09-28T14:14:44.184+0700] {logging_mixin.py:151} INFO - etl_ingest_time_2023_09_28_14_14_44
[2023-09-28T14:14:44.685+0700] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/crawlInvest.py", line 161, in run_my_async_task
    asyncio.run(crawl(Code_stock))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/airflow/dags/crawlInvest.py", line 97, in crawl
    cursor.execute(query_db)
pyodbc.Error: ('HY000', 'The driver did not supply an error!')
[2023-09-28T14:14:44.700+0700] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=crawl_dag_v01, task_id=run_my_async_task, execution_date=20230922T004000, start_date=20230928T071443, end_date=20230928T071444
[2023-09-28T14:14:44.718+0700] {standard_task_runner.py:104} ERROR - Failed to execute job 110 for task run_my_async_task (('HY000', 'The driver did not supply an error!'); 1007)
[2023-09-28T14:14:44.753+0700] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-28T14:14:44.836+0700] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-09-28T14:18:39.317+0700] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crawl_dag_v01.run_my_async_task scheduled__2023-09-22T00:40:00+00:00 [queued]>
[2023-09-28T14:18:39.352+0700] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crawl_dag_v01.run_my_async_task scheduled__2023-09-22T00:40:00+00:00 [queued]>
[2023-09-28T14:18:39.356+0700] {taskinstance.py:1359} INFO - Starting attempt 1 of 6
[2023-09-28T14:18:39.443+0700] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): run_my_async_task> on 2023-09-22 00:40:00+00:00
[2023-09-28T14:18:39.460+0700] {standard_task_runner.py:57} INFO - Started process 1201 to run task
[2023-09-28T14:18:39.569+0700] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'crawl_dag_v01', 'run_my_async_task', 'scheduled__2023-09-22T00:40:00+00:00', '--job-id', '136', '--raw', '--subdir', 'DAGS_FOLDER/crawlInvest.py', '--cfg-path', '/tmp/tmp2hwmr5v7']
[2023-09-28T14:18:39.606+0700] {standard_task_runner.py:85} INFO - Job 136: Subtask run_my_async_task
[2023-09-28T14:18:39.993+0700] {task_command.py:415} INFO - Running <TaskInstance: crawl_dag_v01.run_my_async_task scheduled__2023-09-22T00:40:00+00:00 [running]> on host 052a1d3faae2
[2023-09-28T14:18:40.392+0700] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='linhhv' AIRFLOW_CTX_DAG_ID='crawl_dag_v01' AIRFLOW_CTX_TASK_ID='run_my_async_task' AIRFLOW_CTX_EXECUTION_DATE='2023-09-22T00:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-22T00:40:00+00:00'
[2023-09-28T14:18:40.479+0700] {logging_mixin.py:151} INFO - ['ASG', 'BAX', 'BCF', 'BSA', 'BSH', 'DHB', 'DP2', 'DSG', 'DTK', 'EIC']
[2023-09-28T14:18:40.484+0700] {logging_mixin.py:151} INFO - etl_ingest_time_2023_09_28_14_18_40
[2023-09-28T14:18:41.212+0700] {logging_mixin.py:151} INFO - 10
[2023-09-28T14:18:41.213+0700] {logging_mixin.py:151} INFO - 1
[2023-09-28T14:18:41.241+0700] {logging_mixin.py:151} WARNING -   0%|          | 0/1 [00:00<?, ?it/s]
[2023-09-28T14:18:41.242+0700] {logging_mixin.py:151} INFO - ['ASG', 'BAX', 'BCF', 'BSA', 'BSH', 'DHB', 'DP2', 'DSG', 'DTK', 'EIC']
[2023-09-28T14:18:42.054+0700] {logging_mixin.py:151} INFO - [Empty DataFrame
Columns: []
Index: [],          p    v      cp  rcp   a   ba     sa     hl  pcp         t
0  50200.0  100 -4600.0 -0.1  SD  0.0  100.0  False  0.0  09:00:13, Empty DataFrame
Columns: []
Index: [], Empty DataFrame
Columns: []
Index: [], Empty DataFrame
Columns: []
Index: [], Empty DataFrame
Columns: []
Index: [], Empty DataFrame
Columns: []
Index: [], Empty DataFrame
Columns: []
Index: [],          p    v     cp  rcp   a     ba     sa     hl    pcp         t
0  10700.0  200    0.0  0.0  BU  400.0  100.0  False    0.0  14:03:06
1  10700.0  100    0.0  0.0  BU  200.0  100.0  False    0.0  13:35:59
2  10700.0  100    0.0  0.0  SD  100.0  100.0  False -200.0  10:40:12
3  10900.0  100  200.0  0.0  BU  100.0    0.0  False    0.0  09:57:39, Empty DataFrame
Columns: []
Index: []]
[2023-09-28T14:18:42.055+0700] {logging_mixin.py:151} INFO - hello
[2023-09-28T14:18:42.055+0700] {logging_mixin.py:151} INFO - 10
[2023-09-28T14:18:42.057+0700] {logging_mixin.py:151} WARNING -   0%|          | 0/10 [00:00<?, ?it/s]
[2023-09-28T14:18:42.057+0700] {logging_mixin.py:151} WARNING - 
[2023-09-28T14:18:42.058+0700] {logging_mixin.py:151} INFO - ASG is empty
[2023-09-28T14:18:42.104+0700] {logging_mixin.py:151} INFO -          p    v      cp  rcp   a   ba     sa     hl  pcp         t
0  50200.0  100 -4600.0 -0.1  SD  0.0  100.0  False  0.0  09:00:13
[2023-09-28T14:18:42.127+0700] {logging_mixin.py:151} INFO - DRIVER={ODBC Driver 18 for SQL Server};SERVER=host.docker.internal;DATABASE=etl_ingest_time_2023_09_28_14_18_40;UID=sa;PWD=Docker@123;TrustServerCertificate=yes;
[2023-09-28T14:18:47.226+0700] {base.py:73} INFO - Using connection ID 'minio_s3_conn' for task execution.
[2023-09-28T14:18:47.230+0700] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3_conn', conn_type='aws') credentials retrieved from login and password.
[2023-09-28T14:18:47.508+0700] {logging_mixin.py:151} WARNING -  20%|##        | 2/10 [00:05<00:21,  2.73s/it]
[2023-09-28T14:18:47.509+0700] {logging_mixin.py:151} WARNING - 
[2023-09-28T14:18:47.509+0700] {logging_mixin.py:151} INFO - BCF is empty
[2023-09-28T14:18:47.509+0700] {logging_mixin.py:151} INFO - BSA is empty
[2023-09-28T14:18:47.510+0700] {logging_mixin.py:151} INFO - BSH is empty
[2023-09-28T14:18:47.510+0700] {logging_mixin.py:151} INFO - DHB is empty
[2023-09-28T14:18:47.511+0700] {logging_mixin.py:151} INFO - DP2 is empty
[2023-09-28T14:18:47.511+0700] {logging_mixin.py:151} INFO - DSG is empty
[2023-09-28T14:18:47.517+0700] {logging_mixin.py:151} INFO -          p    v     cp  rcp   a     ba     sa     hl    pcp         t
0  10700.0  200    0.0  0.0  BU  400.0  100.0  False    0.0  14:03:06
1  10700.0  100    0.0  0.0  BU  200.0  100.0  False    0.0  13:35:59
2  10700.0  100    0.0  0.0  SD  100.0  100.0  False -200.0  10:40:12
3  10900.0  100  200.0  0.0  BU  100.0    0.0  False    0.0  09:57:39
[2023-09-28T14:18:47.522+0700] {logging_mixin.py:151} INFO - DRIVER={ODBC Driver 18 for SQL Server};SERVER=host.docker.internal;DATABASE=etl_ingest_time_2023_09_28_14_18_40;UID=sa;PWD=Docker@123;TrustServerCertificate=yes;
[2023-09-28T14:18:47.653+0700] {base.py:73} INFO - Using connection ID 'minio_s3_conn' for task execution.
[2023-09-28T14:18:47.654+0700] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3_conn', conn_type='aws') credentials retrieved from login and password.
[2023-09-28T14:18:47.728+0700] {logging_mixin.py:151} WARNING -  90%|######### | 9/10 [00:05<00:00,  2.08it/s]
[2023-09-28T14:18:47.729+0700] {logging_mixin.py:151} WARNING - 
[2023-09-28T14:18:47.730+0700] {logging_mixin.py:151} INFO - EIC is empty
[2023-09-28T14:18:47.730+0700] {logging_mixin.py:151} WARNING - 100%|##########| 10/10 [00:05<00:00,  1.76it/s]
[2023-09-28T14:18:47.731+0700] {logging_mixin.py:151} INFO - chay lan 1
[2023-09-28T14:18:47.731+0700] {logging_mixin.py:151} INFO - Took 6.49 s
[2023-09-28T14:18:47.732+0700] {logging_mixin.py:151} WARNING - 100%|##########| 1/1 [00:06<00:00,  6.49s/it]
[2023-09-28T14:18:47.732+0700] {logging_mixin.py:151} WARNING - 100%|##########| 1/1 [00:06<00:00,  6.49s/it]
[2023-09-28T14:18:47.733+0700] {logging_mixin.py:151} INFO - DONE CRAWL IN 6.52 s
[2023-09-28T14:18:47.736+0700] {python.py:194} INFO - Done. Returned value was: None
[2023-09-28T14:18:47.750+0700] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=crawl_dag_v01, task_id=run_my_async_task, execution_date=20230922T004000, start_date=20230928T071839, end_date=20230928T071847
[2023-09-28T14:18:47.841+0700] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-28T14:18:47.861+0700] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
